const encode = require("../encode")

test("tests flagpost encodes for all hex values 0-F", () => {
  expect(encode.findClosestFlagpost("0")).toBe("2")
  expect(encode.findClosestFlagpost("1")).toBe("2")
  expect(encode.findClosestFlagpost("2")).toBe("2")
  expect(encode.findClosestFlagpost("3")).toBe("2")
  expect(encode.findClosestFlagpost("4")).toBe("2")
  expect(encode.findClosestFlagpost("5")).toBe("7")
  expect(encode.findClosestFlagpost("6")).toBe("7")
  expect(encode.findClosestFlagpost("7")).toBe("7")
  expect(encode.findClosestFlagpost("8")).toBe("7")
  expect(encode.findClosestFlagpost("9")).toBe("7")
  expect(encode.findClosestFlagpost("a")).toBe("b")
  expect(encode.findClosestFlagpost("b")).toBe("b")
  expect(encode.findClosestFlagpost("c")).toBe("b")
  expect(encode.findClosestFlagpost("d")).toBe("e")
  expect(encode.findClosestFlagpost("e")).toBe("e")
  expect(encode.findClosestFlagpost("f")).toBe("e")
})